### ISSUE TITLE
Spawnable Blocks Not Showing in 1.0-Walked Areas

### ISSUE THREAD

**Issue by kylesutton** [Plethora777/mcpe_viz#15]
Hey Plethora,

I noticed a similar problem to what @Smeo00 was having in #11, where paths I walked since the 1.0 update would show as unexplored chunks.  After a fix you pushed, those chunks now display correctly.  However, the _Spawnable Blocks_ option seems to not show spawnable blocks for those same regions that used to be blacked out.

Here's a screenshot of part of a 180-block radius spawn check around my main area:
![image](https://cloud.githubusercontent.com/assets/11877271/21465243/877ba7f4-c968-11e6-9ff6-048de3ddb994.png)

Thanks for a pretty amazing visualization tool!
Kyle

**Comment by TheDiamondYT1** [comment]
E

**Comment by TheDiamondYT1** [comment]
Whoops

**Comment by Plethora777** [comment]
Hi.  Yep that's a known issue.  The change from all "chunk data in one record" to cubic chunks that occurred with MCPE v1.0 is a big change for mcpe_viz to handle.  I'll have a fix for this soon.  (I miss the functionality too :)

**Comment by Plethora777** [comment]
Just pushed an update which should resolve this.  Give it a try.

**Comment by kylesutton** [comment]
Updated & re-ran the spawn check, with slightly different results:

![image](https://cloud.githubusercontent.com/assets/11877271/21476210/f816fb20-cb03-11e6-97ba-a1db8ea13619.png)

I'm guessing something's still not quite right, as the interior edges of the spawnable regions are still pretty squared.

However, there is an interesting development in the ring of down-arrows towards the center of the checked area.  Here's the zoomed-in default view of that ring:
![image](https://cloud.githubusercontent.com/assets/11877271/21476253/7cfcc40a-cb04-11e6-9bda-cf16020205a3.png)

...here's the same view at layer 127:
![image](https://cloud.githubusercontent.com/assets/11877271/21476263/b5bb7368-cb04-11e6-8bf7-716070487260.png)

...and finally, the view at the layer where the spawn points are actually marked (layer 16):
![image](https://cloud.githubusercontent.com/assets/11877271/21476265/ca834f46-cb04-11e6-8f56-3d11765cbd79.png)

To install updates, I'm just overwriting the files & directories in my _MCPEviz_ directory and overwriting the old map files with the newly generated ones.  Let me know if there's a problem with that scheme that could be leading to these results.

Thanks,
Kyle

**Comment by Plethora777** [comment]
Oh.. Yep.  That didn't quite work out :)  Just published an update that should resolve this.  Give it a try.

**Comment by kylesutton** [comment]
Looks good!

No more squares:
![image](https://cloud.githubusercontent.com/assets/11877271/21512392/1542344e-cc7b-11e6-853a-995bcddbdc76.png)

I have another issue with the spawn check, but I'll open a separate ticket for it, as I don't think it's related to this cubic processing facet.

Thanks!
